#define VMA_IMPLEMENTATION
#define VK_VERSION_1_1
// #define VMA_VULKAN_VERSION 100100
#define VMA_STATIC_VULKAN_FUNCTIONS 0
#define VMA_DYNAMIC_VULKAN_FUNCTIONS 1
#define VMA_DEDICATED_ALLOCATION 0
#define VMA_BIND_MEMORY2 0
#define VMA_MEMORY_BUDGET 0
#include <vk_mem_alloc.h>
