name: ci_readability_check

on:
  push:
    branches:
      - main
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - "**.hpp"
  pull_request:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
      - "**.hpp"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: sudo apt-get install -y mesa-common-dev libsdl2-dev
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: ./scripts/check-readability.py builddir/
  
