name: 'Zig CI'

on:
  push:
    paths:
      - '**.zig'
      - '.github/workflows/zig_test.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.zig'
      - '.github/workflows/zig_test.yml'

jobs:
  compile-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y \
          libglfw3-dev glslang-tools fontconfig
      - run: zig build check
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - run: zig fmt --check src/
